---
- name: Instalar K3s en modo agente (ejemplo mínimo)
  ansible.builtin.shell: |
    curl -sfL https://get.k3s.io | K3S_URL=https://{{ k3s_server_ip }}:6443 K3S_TOKEN={{ k3s_token }} sh -
  args:
    executable: /bin/sh

- name: Instalar kubectl
  ansible.builtin.shell: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && chmod +x kubectl && mv kubectl /usr/bin
  args:
    executable: /bin/sh
