# frozen_string_literal: true

# -*- mode: ruby -*-
# vi: set ft=ruby :
require_relative('lib/lib')

Vagrant.configure('2') do |config|
  config.vm.box = 'generic/alpine319'

  nodes.each do |node|
    config.vm.define node[:name] do |machine|
      machine.vm.hostname = node[:name]
      machine.vm.network 'private_network', ip: node[:network_address]

      machine.vm.provider :libvirt do |lv|
        lv.memory = node[:memory]
        lv.cpus = node[:cpu]
        lv.default_prefix = ''
      end

      machine.vm.provision 'shell', inline: <<-SHELL
         sudo apk update && sudo apk add --no-cache python3 py3-pip
         ln -sf /usr/bin/python3 /usr/bin/python
      SHELL

      machine.vm.provision 'ansible' do |ansible|
        ansible.playbook = 'ansible/playbook.yml'
        ansible.inventory_path = 'ansible/inventory.ini'

        ansible.verbose = 'vvvv'

        ansible.extra_vars = {
          ansible_python_interpreter: '/usr/bin/python3',
          node_type: node[:node_type].to_s
        }
      end
    end
  end
end
