---
- name: "Ensure repository alpine /etc/apk/repositories"
  become: true
  lineinfile:
    path: /etc/apk/repositories
    create: yes
    owner: root
    group: root
    mode: "0644"
    line: "{{ item }}"
    state: present
  loop: "{{ alpine_apk_repositories }}"

- name: package present
  become: true
  package:
    name: "{{ common_packages }}"
    state: present
