---
- name: Install k3s on servers
  hosts: servers
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true
  roles:
    - server

- name: Install k3s on agents
  hosts: agents
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true
  roles:
    - agent

- name: Install kubectl
  hosts: all
  become: true
  vars:
    kubectl_version_url: "https://dl.k8s.io/release/stable.txt"
  roles:
    - common
