---
- name: "copy manifest"
  import_tasks: copy_manifest.yaml
- name: "¡k3s"
  import_tasks: config_k3s.yaml
# # - name: Sincronizar manifiestos
# # #   synchronize:
# #     src: "/"
#     dest: "/"
#     recursive: yes
#     delete: no # no borres YAML antiguos aún
#     notify: apply manifests # dispara el handler si cambia algo
#
# # # - name: Deploy applications deployment to Kubernetes
#   k8s:
#     kubeconfig: /home/vagrant/.kube/config
#     state: present
#     namespace: default
#     definition: "{{ lookup('template', 'deployment.yaml.j2') }}"
#   loop: "{{ apps }}"
#   loop_control:
#     label: "{{ item.name }}"
#
# - name: Deploy applications networking to Kubernetes
#   k8s:
#     kubeconfig: /home/vagrant/.kube/config
#     state: present
#     namespace: default
#     definition: "{{ lookup('template', 'networking.yaml.j2') }}"
#   loop: "{{ apps }}"
#   loop_control:
#     label: "{{ item.name }}"
